import type { Market } from '@/lib/rebalance/types';

export interface StockEntry {
  ticker: string;
  name: string;
  market: Market;
}

/**
 * 자동완성용 종목 리스트 (curated seed 데이터).
 *
 * 코스피/코스닥 전 종목(약 2,500개)과 미국 상장 전종목을 담은 공식 데이터
 * 소스를 이 작업 환경(네트워크가 제한된 샌드박스)에서는 내려받을 수 없어서,
 * 시가총액/거래대금 상위 종목과 주요 ETF 위주로 수동으로 정리했다.
 * 개별주식뿐 아니라 대표적인 ETF들도 포함했지만, 여전히 전종목 대비 일부다.
 *
 * 목록에 없는 종목이라도 티커/종목명을 직접 입력하면 정상적으로 추가할 수
 * 있고, "현재가 조회" 버튼은 이 목록과 무관하게 Yahoo Finance에서 해당
 * 티커를 그대로 조회하기 때문에 목록에 없는 종목도 시세는 정상 조회된다.
 *
 * 이후 정확한 전종목 리스트(KRX 상장법인목록 등)를 구하면 이 배열만
 * 교체/추가하면 된다.
 */
export const KR_STOCKS: StockEntry[] = [
  // --- 대형주 ---
  { ticker: '005930', name: '삼성전자', market: 'KR' },
  { ticker: '000660', name: 'SK하이닉스', market: 'KR' },
  { ticker: '373220', name: 'LG에너지솔루션', market: 'KR' },
  { ticker: '207940', name: '삼성바이오로직스', market: 'KR' },
  { ticker: '005380', name: '현대차', market: 'KR' },
  { ticker: '000270', name: '기아', market: 'KR' },
  { ticker: '005490', name: 'POSCO홀딩스', market: 'KR' },
  { ticker: '051910', name: 'LG화학', market: 'KR' },
  { ticker: '006400', name: '삼성SDI', market: 'KR' },
  { ticker: '035420', name: 'NAVER', market: 'KR' },
  { ticker: '035720', name: '카카오', market: 'KR' },
  { ticker: '068270', name: '셀트리온', market: 'KR' },
  { ticker: '012330', name: '현대모비스', market: 'KR' },
  { ticker: '105560', name: 'KB금융', market: 'KR' },
  { ticker: '055550', name: '신한지주', market: 'KR' },
  { ticker: '086790', name: '하나금융지주', market: 'KR' },
  { ticker: '316140', name: '우리금융지주', market: 'KR' },
  { ticker: '071050', name: '한국금융지주', market: 'KR' },
  { ticker: '138040', name: '메리츠금융지주', market: 'KR' },
  { ticker: '032830', name: '삼성생명', market: 'KR' },
  { ticker: '000810', name: '삼성화재', market: 'KR' },
  { ticker: '001450', name: '현대해상', market: 'KR' },
  { ticker: '005830', name: 'DB손해보험', market: 'KR' },
  { ticker: '024110', name: '기업은행', market: 'KR' },
  { ticker: '029780', name: '삼성카드', market: 'KR' },
  { ticker: '018260', name: '삼성에스디에스', market: 'KR' },
  // --- 인터넷/게임/엔터 ---
  { ticker: '259960', name: '크래프톤', market: 'KR' },
  { ticker: '036570', name: '엔씨소프트', market: 'KR' },
  { ticker: '251270', name: '넷마블', market: 'KR' },
  { ticker: '112040', name: '위메이드', market: 'KR' },
  { ticker: '263750', name: '펄어비스', market: 'KR' },
  { ticker: '293490', name: '카카오게임즈', market: 'KR' },
  { ticker: '095660', name: '네오위즈', market: 'KR' },
  { ticker: '352820', name: '하이브', market: 'KR' },
  { ticker: '035900', name: 'JYP Ent.', market: 'KR' },
  { ticker: '122870', name: '와이지엔터테인먼트', market: 'KR' },
  { ticker: '041510', name: '에스엠', market: 'KR' },
  { ticker: '323410', name: '카카오뱅크', market: 'KR' },
  { ticker: '377300', name: '카카오페이', market: 'KR' },
  // --- 소재/화학/2차전지 ---
  { ticker: '003670', name: '포스코퓨처엠', market: 'KR' },
  { ticker: '096770', name: 'SK이노베이션', market: 'KR' },
  { ticker: '034730', name: 'SK', market: 'KR' },
  { ticker: '010130', name: '고려아연', market: 'KR' },
  { ticker: '247540', name: '에코프로비엠', market: 'KR' },
  { ticker: '086520', name: '에코프로', market: 'KR' },
  { ticker: '066970', name: '엘앤에프', market: 'KR' },
  { ticker: '011790', name: 'SKC', market: 'KR' },
  { ticker: '004020', name: '현대제철', market: 'KR' },
  // --- 조선/중공업/방산 ---
  { ticker: '009540', name: 'HD한국조선해양', market: 'KR' },
  { ticker: '010140', name: '삼성중공업', market: 'KR' },
  { ticker: '267250', name: 'HD현대중공업', market: 'KR' },
  { ticker: '042660', name: '한화오션', market: 'KR' },
  { ticker: '034020', name: '두산에너빌리티', market: 'KR' },
  { ticker: '047810', name: '한국항공우주', market: 'KR' },
  { ticker: '012450', name: '한화에어로스페이스', market: 'KR' },
  { ticker: '079550', name: 'LIG넥스원', market: 'KR' },
  { ticker: '267260', name: 'HD현대일렉트릭', market: 'KR' },
  // --- 정유/에너지/통신 ---
  { ticker: '015760', name: '한국전력', market: 'KR' },
  { ticker: '010950', name: 'S-Oil', market: 'KR' },
  { ticker: '017670', name: 'SK텔레콤', market: 'KR' },
  { ticker: '030200', name: 'KT', market: 'KR' },
  { ticker: '032640', name: 'LG유플러스', market: 'KR' },
  // --- 건설/유통/소비재 ---
  { ticker: '000720', name: '현대건설', market: 'KR' },
  { ticker: '006360', name: 'GS건설', market: 'KR' },
  { ticker: '028050', name: '삼성E&A', market: 'KR' },
  { ticker: '004170', name: '신세계', market: 'KR' },
  { ticker: '023530', name: '롯데쇼핑', market: 'KR' },
  { ticker: '139480', name: '이마트', market: 'KR' },
  { ticker: '007070', name: 'GS리테일', market: 'KR' },
  { ticker: '097950', name: 'CJ제일제당', market: 'KR' },
  { ticker: '090430', name: '아모레퍼시픽', market: 'KR' },
  { ticker: '051900', name: 'LG생활건강', market: 'KR' },
  { ticker: '271560', name: '오리온', market: 'KR' },
  { ticker: '033780', name: 'KT&G', market: 'KR' },
  { ticker: '021240', name: '코웨이', market: 'KR' },
  // --- 전기전자/부품 ---
  { ticker: '066570', name: 'LG전자', market: 'KR' },
  { ticker: '003550', name: 'LG', market: 'KR' },
  { ticker: '009150', name: '삼성전기', market: 'KR' },
  { ticker: '011070', name: 'LG이노텍', market: 'KR' },
  { ticker: '042700', name: '한미반도체', market: 'KR' },
  { ticker: '240810', name: '원익IPS', market: 'KR' },
  { ticker: '084370', name: '유진테크', market: 'KR' },
  { ticker: '018880', name: '한온시스템', market: 'KR' },
  { ticker: '204320', name: '만도', market: 'KR' },
  // --- 운송 ---
  { ticker: '011200', name: 'HMM', market: 'KR' },
  { ticker: '003490', name: '대한항공', market: 'KR' },
  { ticker: '028260', name: '삼성물산', market: 'KR' },
  { ticker: '086280', name: '현대글로비스', market: 'KR' },
  // --- 증권 ---
  { ticker: '005940', name: 'NH투자증권', market: 'KR' },
  { ticker: '016360', name: '삼성증권', market: 'KR' },
  { ticker: '039490', name: '키움증권', market: 'KR' },
  { ticker: '006800', name: '미래에셋증권', market: 'KR' },
  // --- 제약/바이오 ---
  { ticker: '196170', name: '알테오젠', market: 'KR' },
  { ticker: '328130', name: '루닛', market: 'KR' },
  { ticker: '145020', name: '휴젤', market: 'KR' },
  { ticker: '214150', name: '클래시스', market: 'KR' },
  { ticker: '128940', name: '한미약품', market: 'KR' },
  { ticker: '000100', name: '유한양행', market: 'KR' },
  { ticker: '326030', name: 'SK바이오팜', market: 'KR' },
  { ticker: '302440', name: 'SK바이오사이언스', market: 'KR' },
  // --- 지주/기타 ---
  { ticker: '298050', name: '효성첨단소재', market: 'KR' },
  { ticker: '298040', name: '효성중공업', market: 'KR' },
  { ticker: '298020', name: '효성티앤씨', market: 'KR' },
  // --- ETF (코스피/코스닥 대표지수) ---
  { ticker: '069500', name: 'KODEX 200', market: 'KR' },
  { ticker: '102110', name: 'TIGER 200', market: 'KR' },
  { ticker: '148020', name: 'KBSTAR 200', market: 'KR' },
  { ticker: '152100', name: 'ARIRANG 200', market: 'KR' },
  { ticker: '229200', name: 'KODEX 코스닥150', market: 'KR' },
  { ticker: '233740', name: 'KODEX 코스닥150레버리지', market: 'KR' },
  { ticker: '251340', name: 'KODEX 코스닥150선물인버스', market: 'KR' },
  { ticker: '122630', name: 'KODEX 레버리지', market: 'KR' },
  { ticker: '114800', name: 'KODEX 인버스', market: 'KR' },
  { ticker: '252670', name: 'KODEX 200선물인버스2X', market: 'KR' },
  // --- ETF (해외/미국) ---
  { ticker: '360750', name: 'TIGER 미국S&P500', market: 'KR' },
  { ticker: '379800', name: 'KODEX 미국S&P500TR', market: 'KR' },
  { ticker: '133690', name: 'TIGER 미국나스닥100', market: 'KR' },
  { ticker: '381170', name: 'TIGER 미국테크TOP10', market: 'KR' },
  { ticker: '143850', name: 'TIGER 미국S&P500선물(H)', market: 'KR' },
  { ticker: '453850', name: 'TIGER 미국배당다우존스', market: 'KR' },
  { ticker: '456600', name: 'TIGER 미국나스닥100커버드콜(합성)', market: 'KR' },
  { ticker: '245340', name: 'TIGER 차이나CSI300', market: 'KR' },
  { ticker: '371460', name: 'TIGER 차이나전기차SOLACTIVE', market: 'KR' },
  { ticker: '160570', name: 'TIGER 일본니케이225', market: 'KR' },
  // --- ETF (섹터/테마) ---
  { ticker: '305720', name: 'KODEX 2차전지산업', market: 'KR' },
  { ticker: '091160', name: 'KODEX 반도체', market: 'KR' },
  { ticker: '102780', name: 'KODEX 삼성그룹', market: 'KR' },
  { ticker: '117460', name: 'KODEX 에너지화학', market: 'KR' },
  { ticker: '227540', name: 'TIGER 200 헬스케어', market: 'KR' },
  { ticker: '395160', name: 'TIGER 재무제표우량기업', market: 'KR' },
  // --- ETF (채권/원자재) ---
  { ticker: '132030', name: 'KODEX 골드선물(H)', market: 'KR' },
  { ticker: '130680', name: 'TIGER 원유선물Enhanced(H)', market: 'KR' },
  { ticker: '308620', name: 'KODEX 미국채10년선물', market: 'KR' },
  { ticker: '148070', name: 'KODEX 국고채3년', market: 'KR' },
  { ticker: '114260', name: 'KODEX 국고채10년', market: 'KR' },
  { ticker: '182490', name: 'TIGER 단기채권액티브', market: 'KR' },
];

export const US_STOCKS: StockEntry[] = [
  // --- 빅테크/대형주 ---
  { ticker: 'AAPL', name: 'Apple Inc.', market: 'US' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', market: 'US' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', market: 'US' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', market: 'US' },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.', market: 'US' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', market: 'US' },
  { ticker: 'META', name: 'Meta Platforms, Inc.', market: 'US' },
  { ticker: 'TSLA', name: 'Tesla, Inc.', market: 'US' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B', market: 'US' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', market: 'US' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor Mfg.', market: 'US' },
  { ticker: 'ASML', name: 'ASML Holding N.V.', market: 'US' },
  // --- 금융 ---
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', market: 'US' },
  { ticker: 'V', name: 'Visa Inc.', market: 'US' },
  { ticker: 'MA', name: 'Mastercard Incorporated', market: 'US' },
  { ticker: 'BAC', name: 'Bank of America Corporation', market: 'US' },
  { ticker: 'GS', name: 'Goldman Sachs Group, Inc.', market: 'US' },
  { ticker: 'MS', name: 'Morgan Stanley', market: 'US' },
  { ticker: 'WFC', name: 'Wells Fargo & Company', market: 'US' },
  { ticker: 'C', name: 'Citigroup Inc.', market: 'US' },
  { ticker: 'AXP', name: 'American Express Company', market: 'US' },
  { ticker: 'SPGI', name: 'S&P Global Inc.', market: 'US' },
  { ticker: 'BLK', name: 'BlackRock, Inc.', market: 'US' },
  { ticker: 'SCHW', name: 'Charles Schwab Corporation', market: 'US' },
  { ticker: 'PYPL', name: 'PayPal Holdings, Inc.', market: 'US' },
  { ticker: 'COIN', name: 'Coinbase Global, Inc.', market: 'US' },
  // --- 소비재/유통 ---
  { ticker: 'WMT', name: 'Walmart Inc.', market: 'US' },
  { ticker: 'PG', name: 'Procter & Gamble Company', market: 'US' },
  { ticker: 'HD', name: 'Home Depot, Inc.', market: 'US' },
  { ticker: 'LOW', name: "Lowe's Companies, Inc.", market: 'US' },
  { ticker: 'TGT', name: 'Target Corporation', market: 'US' },
  { ticker: 'TJX', name: 'TJX Companies, Inc.', market: 'US' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', market: 'US' },
  { ticker: 'MCD', name: "McDonald's Corporation", market: 'US' },
  { ticker: 'NKE', name: 'Nike, Inc.', market: 'US' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', market: 'US' },
  { ticker: 'DIS', name: 'Walt Disney Company', market: 'US' },
  { ticker: 'NFLX', name: 'Netflix, Inc.', market: 'US' },
  { ticker: 'KO', name: 'Coca-Cola Company', market: 'US' },
  { ticker: 'PEP', name: 'PepsiCo, Inc.', market: 'US' },
  { ticker: 'LULU', name: 'Lululemon Athletica Inc.', market: 'US' },
  { ticker: 'ABNB', name: 'Airbnb, Inc.', market: 'US' },
  { ticker: 'BKNG', name: 'Booking Holdings Inc.', market: 'US' },
  { ticker: 'UBER', name: 'Uber Technologies, Inc.', market: 'US' },
  // --- 에너지 ---
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', market: 'US' },
  { ticker: 'CVX', name: 'Chevron Corporation', market: 'US' },
  // --- 헬스케어 ---
  { ticker: 'JNJ', name: 'Johnson & Johnson', market: 'US' },
  { ticker: 'UNH', name: 'UnitedHealth Group Incorporated', market: 'US' },
  { ticker: 'PFE', name: 'Pfizer Inc.', market: 'US' },
  { ticker: 'MRK', name: 'Merck & Co., Inc.', market: 'US' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', market: 'US' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', market: 'US' },
  { ticker: 'ABT', name: 'Abbott Laboratories', market: 'US' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', market: 'US' },
  { ticker: 'DHR', name: 'Danaher Corporation', market: 'US' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb Company', market: 'US' },
  { ticker: 'GILD', name: 'Gilead Sciences, Inc.', market: 'US' },
  { ticker: 'AMGN', name: 'Amgen Inc.', market: 'US' },
  { ticker: 'ISRG', name: 'Intuitive Surgical, Inc.', market: 'US' },
  // --- 통신/미디어 ---
  { ticker: 'T', name: 'AT&T Inc.', market: 'US' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', market: 'US' },
  // --- 산업재/방산/항공 ---
  { ticker: 'BA', name: 'Boeing Company', market: 'US' },
  { ticker: 'GE', name: 'General Electric Company', market: 'US' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', market: 'US' },
  { ticker: 'MMM', name: '3M Company', market: 'US' },
  { ticker: 'RTX', name: 'RTX Corporation', market: 'US' },
  { ticker: 'LMT', name: 'Lockheed Martin Corporation', market: 'US' },
  { ticker: 'NOC', name: 'Northrop Grumman Corporation', market: 'US' },
  { ticker: 'GD', name: 'General Dynamics Corporation', market: 'US' },
  { ticker: 'DE', name: 'Deere & Company', market: 'US' },
  { ticker: 'HON', name: 'Honeywell International Inc.', market: 'US' },
  { ticker: 'UPS', name: 'United Parcel Service, Inc.', market: 'US' },
  { ticker: 'FDX', name: 'FedEx Corporation', market: 'US' },
  { ticker: 'EMR', name: 'Emerson Electric Co.', market: 'US' },
  { ticker: 'ETN', name: 'Eaton Corporation plc', market: 'US' },
  { ticker: 'F', name: 'Ford Motor Company', market: 'US' },
  { ticker: 'GM', name: 'General Motors Company', market: 'US' },
  { ticker: 'RIVN', name: 'Rivian Automotive, Inc.', market: 'US' },
  // --- 소프트웨어/반도체 ---
  { ticker: 'ADBE', name: 'Adobe Inc.', market: 'US' },
  { ticker: 'CRM', name: 'Salesforce, Inc.', market: 'US' },
  { ticker: 'ORCL', name: 'Oracle Corporation', market: 'US' },
  { ticker: 'INTC', name: 'Intel Corporation', market: 'US' },
  { ticker: 'AMD', name: 'Advanced Micro Devices, Inc.', market: 'US' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', market: 'US' },
  { ticker: 'CSCO', name: 'Cisco Systems, Inc.', market: 'US' },
  { ticker: 'IBM', name: 'International Business Machines', market: 'US' },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated', market: 'US' },
  { ticker: 'AMAT', name: 'Applied Materials, Inc.', market: 'US' },
  { ticker: 'LRCX', name: 'Lam Research Corporation', market: 'US' },
  { ticker: 'MU', name: 'Micron Technology, Inc.', market: 'US' },
  { ticker: 'PANW', name: 'Palo Alto Networks, Inc.', market: 'US' },
  { ticker: 'NOW', name: 'ServiceNow, Inc.', market: 'US' },
  { ticker: 'INTU', name: 'Intuit Inc.', market: 'US' },
  { ticker: 'SHOP', name: 'Shopify Inc.', market: 'US' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', market: 'US' },
  // --- 부동산/유틸리티 ---
  { ticker: 'PLD', name: 'Prologis, Inc.', market: 'US' },
  { ticker: 'AMT', name: 'American Tower Corporation', market: 'US' },
  { ticker: 'EQIX', name: 'Equinix, Inc.', market: 'US' },
  { ticker: 'SPG', name: 'Simon Property Group, Inc.', market: 'US' },
  { ticker: 'SO', name: 'Southern Company', market: 'US' },
  { ticker: 'DUK', name: 'Duke Energy Corporation', market: 'US' },
  { ticker: 'NEE', name: 'NextEra Energy, Inc.', market: 'US' },
  // --- ETF (지수) ---
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust', market: 'US' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', market: 'US' },
  { ticker: 'IVV', name: 'iShares Core S&P 500 ETF', market: 'US' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust', market: 'US' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', market: 'US' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF', market: 'US' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', market: 'US' },
  { ticker: 'VB', name: 'Vanguard Small-Cap ETF', market: 'US' },
  { ticker: 'VO', name: 'Vanguard Mid-Cap ETF', market: 'US' },
  { ticker: 'IJH', name: 'iShares Core S&P Mid-Cap ETF', market: 'US' },
  { ticker: 'IJR', name: 'iShares Core S&P Small-Cap ETF', market: 'US' },
  // --- ETF (레버리지/테마) ---
  { ticker: 'ARKK', name: 'ARK Innovation ETF', market: 'US' },
  { ticker: 'TQQQ', name: 'ProShares UltraPro QQQ', market: 'US' },
  { ticker: 'SQQQ', name: 'ProShares UltraPro Short QQQ', market: 'US' },
  { ticker: 'SOXX', name: 'iShares Semiconductor ETF', market: 'US' },
  { ticker: 'SOXL', name: 'Direxion Daily Semiconductor Bull 3X', market: 'US' },
  { ticker: 'SMH', name: 'VanEck Semiconductor ETF', market: 'US' },
  { ticker: 'UPRO', name: 'ProShares UltraPro S&P500', market: 'US' },
  // --- ETF (섹터 SPDR) ---
  { ticker: 'XLK', name: 'Technology Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLY', name: 'Consumer Discretionary Select Sector SPDR', market: 'US' },
  { ticker: 'XLP', name: 'Consumer Staples Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLU', name: 'Utilities Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLB', name: 'Materials Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLC', name: 'Communication Services Select SPDR', market: 'US' },
  // --- ETF (채권/원자재) ---
  { ticker: 'GLD', name: 'SPDR Gold Shares', market: 'US' },
  { ticker: 'SLV', name: 'iShares Silver Trust', market: 'US' },
  { ticker: 'USO', name: 'United States Oil Fund', market: 'US' },
  { ticker: 'DBC', name: 'Invesco DB Commodity Index Tracking Fund', market: 'US' },
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', market: 'US' },
  { ticker: 'IEF', name: 'iShares 7-10 Year Treasury Bond ETF', market: 'US' },
  { ticker: 'SHY', name: 'iShares 1-3 Year Treasury Bond ETF', market: 'US' },
  { ticker: 'AGG', name: 'iShares Core U.S. Aggregate Bond ETF', market: 'US' },
  { ticker: 'BND', name: 'Vanguard Total Bond Market ETF', market: 'US' },
  { ticker: 'LQD', name: 'iShares iBoxx Investment Grade Corp Bond', market: 'US' },
  { ticker: 'HYG', name: 'iShares iBoxx High Yield Corp Bond ETF', market: 'US' },
  // --- ETF (배당/해외) ---
  { ticker: 'SCHD', name: 'Schwab US Dividend Equity ETF', market: 'US' },
  { ticker: 'VYM', name: 'Vanguard High Dividend Yield ETF', market: 'US' },
  { ticker: 'VIG', name: 'Vanguard Dividend Appreciation ETF', market: 'US' },
  { ticker: 'DVY', name: 'iShares Select Dividend ETF', market: 'US' },
  { ticker: 'HDV', name: 'iShares Core High Dividend ETF', market: 'US' },
  { ticker: 'VNQ', name: 'Vanguard Real Estate ETF', market: 'US' },
  { ticker: 'VXUS', name: 'Vanguard Total International Stock ETF', market: 'US' },
  { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', market: 'US' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF', market: 'US' },
  { ticker: 'EWJ', name: 'iShares MSCI Japan ETF', market: 'US' },
  { ticker: 'EWY', name: 'iShares MSCI South Korea ETF', market: 'US' },
  { ticker: 'FXI', name: 'iShares China Large-Cap ETF', market: 'US' },
  { ticker: 'MCHI', name: 'iShares MSCI China ETF', market: 'US' },
];
