import type { Market } from '@/lib/rebalance/types';

export interface StockEntry {
  ticker: string;
  name: string;
  market: Market;
}

/**
 * 자동완성용 종목 리스트 (curated seed 데이터).
 *
 * 코스피/코스닥 전 종목(약 2,500개)을 담은 공식 데이터 소스를 이 작업 환경에서는
 * 내려받을 수 없어서, 우선 시가총액 상위/거래대금 상위 종목과 대표 ETF 위주로
 * 수동으로 정리했다. 자동완성은 어디까지나 "편의 기능"이라 목록에 없는 종목도
 * 티커/종목명을 직접 입력하면 정상적으로 추가할 수 있다.
 *
 * 이후 정확한 전종목 리스트(KRX 상장법인목록 등)를 구하면 이 배열만 교체하면 된다.
 */
export const KR_STOCKS: StockEntry[] = [
  { ticker: '005930', name: '삼성전자', market: 'KR' },
  { ticker: '000660', name: 'SK하이닉스', market: 'KR' },
  { ticker: '373220', name: 'LG에너지솔루션', market: 'KR' },
  { ticker: '207940', name: '삼성바이오로직스', market: 'KR' },
  { ticker: '005380', name: '현대차', market: 'KR' },
  { ticker: '000270', name: '기아', market: 'KR' },
  { ticker: '005490', name: 'POSCO홀딩스', market: 'KR' },
  { ticker: '051910', name: 'LG화학', market: 'KR' },
  { ticker: '006400', name: '삼성SDI', market: 'KR' },
  { ticker: '035420', name: 'NAVER', market: 'KR' },
  { ticker: '035720', name: '카카오', market: 'KR' },
  { ticker: '068270', name: '셀트리온', market: 'KR' },
  { ticker: '012330', name: '현대모비스', market: 'KR' },
  { ticker: '105560', name: 'KB금융', market: 'KR' },
  { ticker: '055550', name: '신한지주', market: 'KR' },
  { ticker: '086790', name: '하나금융지주', market: 'KR' },
  { ticker: '316140', name: '우리금융지주', market: 'KR' },
  { ticker: '032830', name: '삼성생명', market: 'KR' },
  { ticker: '018260', name: '삼성에스디에스', market: 'KR' },
  { ticker: '259960', name: '크래프톤', market: 'KR' },
  { ticker: '036570', name: '엔씨소프트', market: 'KR' },
  { ticker: '251270', name: '넷마블', market: 'KR' },
  { ticker: '003670', name: '포스코퓨처엠', market: 'KR' },
  { ticker: '096770', name: 'SK이노베이션', market: 'KR' },
  { ticker: '034730', name: 'SK', market: 'KR' },
  { ticker: '015760', name: '한국전력', market: 'KR' },
  { ticker: '066570', name: 'LG전자', market: 'KR' },
  { ticker: '003550', name: 'LG', market: 'KR' },
  { ticker: '010130', name: '고려아연', market: 'KR' },
  { ticker: '011200', name: 'HMM', market: 'KR' },
  { ticker: '097950', name: 'CJ제일제당', market: 'KR' },
  { ticker: '009150', name: '삼성전기', market: 'KR' },
  { ticker: '042700', name: '한미반도체', market: 'KR' },
  { ticker: '293490', name: '카카오게임즈', market: 'KR' },
  { ticker: '041510', name: '에스엠', market: 'KR' },
  { ticker: '352820', name: '하이브', market: 'KR' },
  { ticker: '035900', name: 'JYP Ent.', market: 'KR' },
  { ticker: '122870', name: '와이지엔터테인먼트', market: 'KR' },
  { ticker: '323410', name: '카카오뱅크', market: 'KR' },
  { ticker: '377300', name: '카카오페이', market: 'KR' },
  { ticker: '018880', name: '한온시스템', market: 'KR' },
  { ticker: '028260', name: '삼성물산', market: 'KR' },
  { ticker: '033780', name: 'KT&G', market: 'KR' },
  { ticker: '030200', name: 'KT', market: 'KR' },
  { ticker: '017670', name: 'SK텔레콤', market: 'KR' },
  { ticker: '032640', name: 'LG유플러스', market: 'KR' },
  { ticker: '024110', name: '기업은행', market: 'KR' },
  { ticker: '138040', name: '메리츠금융지주', market: 'KR' },
  { ticker: '000810', name: '삼성화재', market: 'KR' },
  { ticker: '021240', name: '코웨이', market: 'KR' },
  { ticker: '047810', name: '한국항공우주', market: 'KR' },
  { ticker: '012450', name: '한화에어로스페이스', market: 'KR' },
  { ticker: '079550', name: 'LIG넥스원', market: 'KR' },
  { ticker: '010140', name: '삼성중공업', market: 'KR' },
  { ticker: '009540', name: 'HD한국조선해양', market: 'KR' },
  { ticker: '267250', name: 'HD현대중공업', market: 'KR' },
  { ticker: '011070', name: 'LG이노텍', market: 'KR' },
  { ticker: '090430', name: '아모레퍼시픽', market: 'KR' },
  { ticker: '051900', name: 'LG생활건강', market: 'KR' },
  { ticker: '271560', name: '오리온', market: 'KR' },
  { ticker: '004020', name: '현대제철', market: 'KR' },
  { ticker: '010950', name: 'S-Oil', market: 'KR' },
  { ticker: '267260', name: 'HD현대일렉트릭', market: 'KR' },
  { ticker: '034020', name: '두산에너빌리티', market: 'KR' },
  { ticker: '000720', name: '현대건설', market: 'KR' },
  { ticker: '028050', name: '삼성E&A', market: 'KR' },
  { ticker: '086280', name: '현대글로비스', market: 'KR' },
  { ticker: '005940', name: 'NH투자증권', market: 'KR' },
  { ticker: '016360', name: '삼성증권', market: 'KR' },
  { ticker: '039490', name: '키움증권', market: 'KR' },
  { ticker: '006800', name: '미래에셋증권', market: 'KR' },
  { ticker: '298050', name: '효성첨단소재', market: 'KR' },
  { ticker: '298040', name: '효성중공업', market: 'KR' },
  { ticker: '298020', name: '효성티앤씨', market: 'KR' },
  { ticker: '196170', name: '알테오젠', market: 'KR' },
  { ticker: '328130', name: '루닛', market: 'KR' },
  { ticker: '145020', name: '휴젤', market: 'KR' },
  { ticker: '214150', name: '클래시스', market: 'KR' },
  { ticker: '108860', name: '셀바스AI', market: 'KR' },
  { ticker: '247540', name: '에코프로비엠', market: 'KR' },
  { ticker: '086520', name: '에코프로', market: 'KR' },
  { ticker: '066970', name: '엘앤에프', market: 'KR' },
  { ticker: '112040', name: '위메이드', market: 'KR' },
  { ticker: '263750', name: '펄어비스', market: 'KR' },
  { ticker: '095660', name: '네오위즈', market: 'KR' },
  { ticker: '069500', name: 'KODEX 200', market: 'KR' },
  { ticker: '102110', name: 'TIGER 200', market: 'KR' },
  { ticker: '148020', name: 'KBSTAR 200', market: 'KR' },
  { ticker: '229200', name: 'KODEX 코스닥150', market: 'KR' },
  { ticker: '233740', name: 'KODEX 코스닥150레버리지', market: 'KR' },
  { ticker: '360750', name: 'TIGER 미국S&P500', market: 'KR' },
  { ticker: '379800', name: 'KODEX 미국S&P500TR', market: 'KR' },
  { ticker: '133690', name: 'TIGER 미국나스닥100', market: 'KR' },
  { ticker: '381170', name: 'TIGER 미국테크TOP10', market: 'KR' },
  { ticker: '143850', name: 'TIGER 미국S&P500선물(H)', market: 'KR' },
  { ticker: '305720', name: 'KODEX 2차전지산업', market: 'KR' },
  { ticker: '091160', name: 'KODEX 반도체', market: 'KR' },
  { ticker: '102780', name: 'KODEX 삼성그룹', market: 'KR' },
  { ticker: '114800', name: 'KODEX 인버스', market: 'KR' },
  { ticker: '252670', name: 'KODEX 200선물인버스2X', market: 'KR' },
  { ticker: '132030', name: 'KODEX 골드선물(H)', market: 'KR' },
  { ticker: '130680', name: 'TIGER 원유선물Enhanced(H)', market: 'KR' },
  { ticker: '308620', name: 'KODEX 미국채10년선물', market: 'KR' },
  { ticker: '453850', name: 'TIGER 미국배당다우존스', market: 'KR' },
  { ticker: '456600', name: 'TIGER 미국나스닥100커버드콜(합성)', market: 'KR' },
];

export const US_STOCKS: StockEntry[] = [
  { ticker: 'AAPL', name: 'Apple Inc.', market: 'US' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', market: 'US' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', market: 'US' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', market: 'US' },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.', market: 'US' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', market: 'US' },
  { ticker: 'META', name: 'Meta Platforms, Inc.', market: 'US' },
  { ticker: 'TSLA', name: 'Tesla, Inc.', market: 'US' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B', market: 'US' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', market: 'US' },
  { ticker: 'V', name: 'Visa Inc.', market: 'US' },
  { ticker: 'MA', name: 'Mastercard Incorporated', market: 'US' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', market: 'US' },
  { ticker: 'WMT', name: 'Walmart Inc.', market: 'US' },
  { ticker: 'PG', name: 'Procter & Gamble Company', market: 'US' },
  { ticker: 'HD', name: 'Home Depot, Inc.', market: 'US' },
  { ticker: 'DIS', name: 'Walt Disney Company', market: 'US' },
  { ticker: 'NFLX', name: 'Netflix, Inc.', market: 'US' },
  { ticker: 'KO', name: 'Coca-Cola Company', market: 'US' },
  { ticker: 'PEP', name: 'PepsiCo, Inc.', market: 'US' },
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', market: 'US' },
  { ticker: 'CVX', name: 'Chevron Corporation', market: 'US' },
  { ticker: 'BAC', name: 'Bank of America Corporation', market: 'US' },
  { ticker: 'ADBE', name: 'Adobe Inc.', market: 'US' },
  { ticker: 'CRM', name: 'Salesforce, Inc.', market: 'US' },
  { ticker: 'ORCL', name: 'Oracle Corporation', market: 'US' },
  { ticker: 'INTC', name: 'Intel Corporation', market: 'US' },
  { ticker: 'AMD', name: 'Advanced Micro Devices, Inc.', market: 'US' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', market: 'US' },
  { ticker: 'CSCO', name: 'Cisco Systems, Inc.', market: 'US' },
  { ticker: 'IBM', name: 'International Business Machines', market: 'US' },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated', market: 'US' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', market: 'US' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', market: 'US' },
  { ticker: 'MCD', name: "McDonald's Corporation", market: 'US' },
  { ticker: 'NKE', name: 'Nike, Inc.', market: 'US' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', market: 'US' },
  { ticker: 'BA', name: 'Boeing Company', market: 'US' },
  { ticker: 'GE', name: 'General Electric Company', market: 'US' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', market: 'US' },
  { ticker: 'MMM', name: '3M Company', market: 'US' },
  { ticker: 'UNH', name: 'UnitedHealth Group Incorporated', market: 'US' },
  { ticker: 'PFE', name: 'Pfizer Inc.', market: 'US' },
  { ticker: 'MRK', name: 'Merck & Co., Inc.', market: 'US' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', market: 'US' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', market: 'US' },
  { ticker: 'T', name: 'AT&T Inc.', market: 'US' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', market: 'US' },
  { ticker: 'PYPL', name: 'PayPal Holdings, Inc.', market: 'US' },
  { ticker: 'UBER', name: 'Uber Technologies, Inc.', market: 'US' },
  { ticker: 'SHOP', name: 'Shopify Inc.', market: 'US' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', market: 'US' },
  { ticker: 'COIN', name: 'Coinbase Global, Inc.', market: 'US' },
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust', market: 'US' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust', market: 'US' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', market: 'US' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', market: 'US' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF', market: 'US' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', market: 'US' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF', market: 'US' },
  { ticker: 'GLD', name: 'SPDR Gold Shares', market: 'US' },
  { ticker: 'SLV', name: 'iShares Silver Trust', market: 'US' },
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', market: 'US' },
  { ticker: 'SCHD', name: 'Schwab US Dividend Equity ETF', market: 'US' },
  { ticker: 'VYM', name: 'Vanguard High Dividend Yield ETF', market: 'US' },
  { ticker: 'VXUS', name: 'Vanguard Total International Stock ETF', market: 'US' },
  { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', market: 'US' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF', market: 'US' },
  { ticker: 'XLK', name: 'Technology Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR Fund', market: 'US' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR Fund', market: 'US' },
  { ticker: 'SMH', name: 'VanEck Semiconductor ETF', market: 'US' },
  { ticker: 'SOXX', name: 'iShares Semiconductor ETF', market: 'US' },
];
